### ISSUE TITLE
models.permalink() decorator has been removed from Django since version 2.1

### ISSUE THREAD

**Issue by jeromecc** [aneumeier/category#2]
Hello!

models.permalink() decorator is deprecated since Django 1.1 and has been remove from 2.1
Trying to use category with Django 2.1 or 2.2 gives this error:
```
category/category/models.py", line 106, in Tag
    @models.permalink
AttributeError: module 'django.db.models' has no attribute 'permalink'
```
A fix is suggested here: https://docs.djangoproject.com/en/2.1/releases/1.11/#features-deprecated-in-1-11

Thanks.

**Comment by andreasofthings** [comment]
Thanks for pointing out. Actually, this effort with category was abandoned in favour of moving into `feeds` directly.
